---
apiVersion: v1
kind: Service
metadata:
  name: was-traditional-service
spec:
  type: NodePort
  selector:
    app: was-traditional
  ports:
  - name: "9043"
    port: 9043
    targetPort: 9043
    nodePort: 30001  
  - name: "9443"
    port: 9443
    targetPort: 9443
    nodePort: 30002
         
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: was-traditional
spec:
  selector:
    matchLabels:
      app: was-traditional

  template: 
    metadata:
      labels:
        app: was-traditional
    spec:
      containers:
        - image: miya/wastraditional:1.0
          name: was-traditional
          ports:
          - containerPort: 9043
          - containerPort: 9443
